### ISSUE TITLE
Kaldi requires openfst

### ISSUE THREAD

**Issue by gitfoxi** [claritylab/sirius#25]
It doesn't seem like installing openfst is scripted. My first thought is to go download the source:

http://www.openfst.org/twiki/bin/view/FST/FstDownload

We'll see how that works out for me.

**Comment by gitfoxi** [comment]
Maybe a better idea is to go to:

sirius-application/speech-recognition/kaldi/tools

and fight wiith the make file until it builds all the dependencies.

**Comment by gitfoxi** [comment]
Probably the root issue is that these installation scripts should error out at the first sign of trouble. Instead, they keep plugging away and you won't notice if a step failed to complete before the next one starts.

**Comment by gitfoxi** [comment]
Then you may want to install CUDA: `sudo aptitude install nvidia-cuda-dev nvidia-cuda-toolkit`

Then you may want to run the speex installer: `./install_speex.sh` It sort of fails but sort of succeeds.

**Comment by gitfoxi** [comment]
Don't forget to install sox or kaldi server will suck:

'sudo aptitude install sox'

**Comment by CaptSpify** [comment]
I had issues getting this working on a raspberry pi. I was getting: 
"***configure failed: Could not find file /include/fst/fst.h:
    you may not have installed OpenFst.  See ../tools/INSTALL ***"

I had to edit: speech-recognition/kaldi/src/kaldi.mk and remove the "-msse -msse2" flags on line 40. From there I was able to ./configure
From what I've read, those flags are for x86. 

I'd submit a pull-request for this, but I can't as the fst.h is part of src.tar.gz

**Comment by hurricane92** [comment]
1. I tried same thing on 'kaldi.mk'.

2. But 'kaldi/src/configure' leave same message :
"**configure failed: Could not find file /include/fst/fst.h:
you may not have installed OpenFst. See ../tools/INSTALL **"

3. And I followed '../tools/INSTALL-(2)Install instuctions for OpenFst'
![sirius howto install openfst](https://cloud.githubusercontent.com/assets/13096272/8412002/f136918e-1ec1-11e5-81bd-d260f94bb81e.PNG)

3-1. (error)
command : openfst-1.3.2/src/include/fst& [ -d &dir ] && cd &dir && patch -p0 -N <../../../../openfst.patch
result : there is no openfst.patch

3-2. (error)
command : ./configure --prefix='pwd' --enable-static --disable-shared
result : Configure: error: expected an absolute directory name for –prefix: pwd
My action : erase '-prefix: pwd' on the command

4. Then I compiled sirius-servers again.
And I got same message :
"**configure failed: Could not find file /include/fst/fst.h:
you may not have installed OpenFst. See ../tools/INSTALL **"

How can I do? thanks to read.

**Comment by cdmeister** [comment]
Hey

when you go into the tools folder, just type "make" in the cmd line. then go back and execute the compile sirius servers script  That is what I normally do.

**Comment by hurricane92** [comment]
Thanks you very much! You gave me clear answer.

After it, I got another issue about 'sirius-asr-test'.
Would you mind talking about it by e-mail? or on another issue.

**Comment by cdmeister** [comment]
You can open up another issue I will close this one then
