### ISSUE TITLE
sirius unix command shell

### ISSUE THREAD

**Issue by d4ndo** [claritylab/sirius#56]
I'm working on a sirius client written in C and libcurl.

```
Usage: sirius [OPTION]... QUESTION ...

  [QUESTION]   QUESTION to ask sirius.
               If it is not specified, data will be
               taken from standard input.

  -a, --speechrecog [WAV FILE]
               WAV_FILE some voice audio file for sirius to recognice.

  -i, --imagematch [IMAGE_FILE]
               IMAGE_FILE some image file for sirius to match.

  -u, --url [URL]
               URL from sirius host..

  -c, --cert [CERTIFICATE_FILE]
               CERTIFICATE_FILE the certificate for sirius host.

  -v, --version
               Display the version number of sirius.

      --verbose
               Display verbose information to stderr.

  -h, --help   Display this help message.

```

This would allow to pipe questions to sirius:

```bash
echo "What is this?" | sirius -i ./eifel_tower.bmp

#Maybe it should answer voice recognition by default if no other flag is set.
sirius -s ./capital_of_italy.wav | sirius 
```

**Comment by d4ndo** [comment]
First release:

https://github.com/d4ndo/sirius-client

At least the »question answer« part is implemented already.

Have fun.

**Comment by jhauswald** [comment]
Hey, just tested it works great. Keep us updated with your progress especially once you implement the image and speech component. This could definitely be used in place of some of the scripts we are currently user.

Thanks!

**Comment by d4ndo** [comment]
The image and speech components have been extended.

It took me a while to understand that the python web server does not accept `multipart/formdata`. Not like the java web server for sphinx4 (supports both).

e.G. using curl, this is correct:

```bash
curl -H "Content-Type: audio/vnd.wave; rate=16000" --data-binary @what.is.the.capital.of.italy.wav localhost:8081
```

No --form flag.
