### ISSUE TITLE
Error using Kaldi server: "error opening stream null"

### ISSUE THREAD

**Issue by aolney** [claritylab/sirius#76]
I'm trying to use the python server directly (as below). Once started, I use sirius-asr-test.sh with a wav file in another terminal. At that point, the WARNING and errors below appear.

I checked the kaldi support pages and couldn't really find anything to explain why 'scp:echo utterance-id1 null|' is a problem.

Any ideas?

```
./start-asr-dnn-server.py localhost 8081
Starting server on localhost:8081, use <Ctrl-C> to stop
../kaldi-trunk/src/online2bin/online2-wav-nnet2-latgen-faster --do-endpointing=false --online=true --config=../kaldi-trunk/nnet_a_gpu_online/conf/online_nnet2_decoding.conf --max-active=7000 --beam=15.0 --lattice-beam=6.0 --acoustic-scale=0.1 --word-symbol-table=../kaldi-trunk/graph/words.txt ../kaldi-trunk/nnet_a_gpu_online/smbr_epoch2.mdl ../kaldi-trunk/graph/HCLG.fst 'ark:echo utterance-id1 utterance-id1|' 'scp:echo utterance-id1 null|' ark:/dev/null 
LOG (online2-wav-nnet2-latgen-faster:ComputeDerivedVars():ivector-extractor.cc:180) Computing derived variables for iVector extractor
LOG (online2-wav-nnet2-latgen-faster:ComputeDerivedVars():ivector-extractor.cc:201) Done.
WARNING (online2-wav-nnet2-latgen-faster:HasKeyInternal():util/kaldi-table-inl.h:1359) RandomAccessTableReader: error opening stream null
ERROR (online2-wav-nnet2-latgen-faster:Value():util/kaldi-table-inl.h:1309) RandomAccessTableReader::Value(), could not get item for key utterance-id1, rspecifier is scp:echo utterance-id1 null|[to ignore this , add the p, (permissive) option to the rspecifier.
ERROR (online2-wav-nnet2-latgen-faster:Value():util/kaldi-table-inl.h:1309) RandomAccessTableReader::Value(), could not get item for key utterance-id1, rspecifier is scp:echo utterance-id1 null|[to ignore this , add the p, (permissive) option to the rspecifier.

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
kaldi::RandomAccessTableReaderScriptImpl<kaldi::WaveHolder>::Value(std::string const&)
kaldi::RandomAccessTableReader<kaldi::WaveHolder>::Value(std::string const&)
../kaldi-trunk/src/online2bin/online2-wav-nnet2-latgen-faster(main+0x831) [0x650192]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f0662563b45]
../kaldi-trunk/src/online2bin/online2-wav-nnet2-latgen-faster() [0x64f372]
```

**Comment by ypkang** [comment]
It seems the sever can not find the wav file to decode. If the it works properly, the output should be something like "Wavfile name received. Decoding ../../input-log/8k_input-14222.wav" instead of the WARNING and ERRORs.

Can you post your command on the other terminal where you run sirius-asr-test.sh ?

**Comment by aolney** [comment]
Ok, my apologies. I just realized that it throws this error just by starting the server script, though with some delay. So running sirius-asr-test.sh is not necessary.

BTW I already had a working kaldi fisher english installation, so I didn't use your install scripts.

However, my version of decode.sh works fine. It looks like this

```
KALDI_DIR=../kaldi-trunk

WAV_FILE=$1

$KALDI_DIR/src/online2bin/online2-wav-nnet2-latgen-faster \
  --do-endpointing=false --online=false \
  --config=$KALDI_DIR/nnet_a_gpu_online/conf/online_nnet2_decoding.conf \
  --max-active=7000 --beam=15.0 --lattice-beam=6.0 \
  --acoustic-scale=0.1 --word-symbol-table=$KALDI_DIR/graph/words.txt \
  $KALDI_DIR/nnet_a_gpu_online/smbr_epoch2.mdl $KALDI_DIR/graph/HCLG.fst \
  "ark:echo utterance-id1 utterance-id1|" "scp:echo utterance-id1 $WAV_FILE|" \
  ark:/dev/null
```

And my server.sh looks like this:

```
KALDI_DIR=../kaldi-trunk

$KALDI_DIR/src/online2bin/online2-wav-nnet2-latgen-faster \
  --do-endpointing=false --online=true \
  --config=$KALDI_DIR/nnet_a_gpu_online/conf/online_nnet2_decoding.conf \
  --max-active=7000 --beam=15.0 --lattice-beam=6.0 \
  --acoustic-scale=0.1 --word-symbol-table=$KALDI_DIR/graph/words.txt \
  $KALDI_DIR/nnet_a_gpu_online/smbr_epoch2.mdl $KALDI_DIR/graph/HCLG.fst \
  "ark:echo utterance-id1 utterance-id1|" "scp:echo utterance-id1 null|" \
  ark:/dev/null
```

So the only two differences I see are that in server.sh, online=true and the scp uses null instead of a wav file.

My guess is that the problem is with null, e.g. with "scp:echo utterance-id1 null|"

What is "null" here? Should it be /dev/null? I'm on Debian unstable BTW

**Comment by ypkang** [comment]
Are you using the source code in src.tar.gz included in the repo ? Because in order to make it function like a server and able to receive and process request query, we modify the kaldi source code. Instead of taking the name of the audio file as an argument, it now load up the required model and wait for the name of the target wav file name from cin. And that's why when the server starts, we just pass in null.

**Comment by aolney** [comment]
That explains it -- I didn't realize you had modified the source code for kaldi. I just wanted to use your server script as a wrapper around my existing kaldi fisher english.

I've downloaded/compiled with your src.tar.gz and tools.tar.gz, and now everything works.

Sorry for the confusion

**Comment by ypkang** [comment]
No problem. I'm glad to see it is working now :) I am closing this issue.

**Comment by Hangphuong** [comment]
I had same error like you. So I want to know how to you solve this error, Mr Andrew M Olney
